version: '3.5'

networks:
  app-net:
    driver: bridge

services:
  nginx:
    container_name: nginx-timemap
    image: bitnami/nginx:${NGINX_VERSION}-${OS_VERSION}
    restart: always
    environment:
      - 'TZ=${TIMEZONE}'
    networks:
      - app-net
    ports: 
      - "80:8081"
      - "443:8443"
    volumes:
      - ./public-html:/app:rw
      - ./config/nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:rw
      - ./config/nginx/vhost:/opt/bitnami/nginx/conf/vhosts:rw
      - ./logs/nginx/${NGINX_VERSION}:/opt/bitnami/nginx/logs:rw
    links:
      - redis

  redis:
    build: ./redis
    container_name: redis-server
    restart: always
    tty: true
    ports:
      - "6379:6379"
    working_dir: /data
    volumes:
      - ./etc/localtime:/etc/localtime
    networks:
      - app-net
